---
- name: Build MongoDB cluster
  hosts: tag_server_type_mongodb
  roles:
    - base

- name: Build Config Replicaset
  hosts: tag_rs_type_config
  roles:
    - config_replicaset

- name: Build Data node Replicaset
  hosts: "{{ items }}"
  roles:
    - data_node_replicaset
  vars:
    host_group: "{{ items }}"
  with_items:
    - tag_replica_set_1
    - tag_replica_set_2
    - tag_replica_set_3
