---
- name: Create config server config file from template
  template:
    src: mongod_without_security.conf.template
    dest: /etc/mongod.conf
  notify:
    - restart mongod

- name: Config server replicaset
  community.mongodb.mongodb_replicaset:
    login_host: localhost:{{ shard_port }}
    replica_set: rs-cfg
    members: "{{ config_members }}"
  when: ansible_facts.ansible_local.custom.mongodb.rs_primary == "true"

#- name: Create admin user
#  mongodb_user:
#    database: admin
#    name: {{ admin_user }}
#    password: {{ admin_password }}
#    roles:
#      - db: admin
#        role: root
#    state: present
#  when: ansible_facts.ansible_local.custom.mongodb.rs_primary == "true"

