---
- name: Add mongodb package repository
  apt_repository:
    repo: https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse
    state: present

- name: Update apt repository cache
  apt:
    update_cache: yes

- name: Convert Timezone to KST
  timezone:
    name: Asia/Seoul

- name: Install chrony
  apt:
    name: chrony
    state: present

- name: Creates chrony directory
  file:
    path: /etc/chrony
    state: directory

- name: Create ntp config file from template
  template:
    src: chrony.conf.template
    dest: /etc/chrony/chrony.conf
  notify:
    - restart chrony

- name: Create xfs filesystem on data disk blocks
  filesystem:
    fstype: xfs
    dev: /dev/{{ data_disk_device_name }}
  when: data_disk_device_name in ansible_devices

- name: Creates data volume directory
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /data
    - /data/mongo

- name: Mount and bind a volume
  mount:
    path: /data/mongo
    src: /dev/{{ data_disk_device_name }}
    fstype: xfs
    state: mounted
